version: '3.8'

services:

  db:
    image: mysql
    container_name: MySQL_Container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bucketlist
      MYSQL_USER: ric 
      MYSQL_PASSWORD: 123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app: 
    build: .
    container_name: Main_Container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bucketlist
      DB_USER: ric
      DB_PASSWORD: 123456
    ports:
      - 5000:5000
    links:
    - db
    command: python app.py